apiVersion: apps/v1
kind: Deployment

metadata:
  name: inventario-app

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: inventario-app

  template:
    metadata:
      labels:
        app: inventario-app

    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/pedrogonzalez2207/inventario-app-cicd:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          env:
            - name: STARTUP_DELAY_SECONDS
              value: "15"    

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3